### PR TITLE
Compatibility fix for RequireJS / AMD Issue #35

### PR DESCRIPTION
**Pull request by jogi**
This is a fix to Issue #35. It makes ICanHaz compatible with Require.js as well as its backwards compatible. Has passed all the qunit tests.

### CODE REVIEW

**Comment by jogi** [comment]
@HenrikJoreteg any inputs?

**Comment by treasonx** [comment]
+1

This looks much better. Just helped with a problem in the requirejs IRC channel and they needed this pull request to get things working properly.

**Comment by herringtown** [comment]
this fix seems to do the trick (whereas using ich as a package, or shimmed ich failed).... @HenrikJoreteg , anything stopping you from incorporating this fix?

**Comment by HenrikJoreteg** [comment]
Hey, all. I feel terrible about the fact that I'm letting this stuff just sit. I can't actually devote the necessary time to this that it deserves. I simply have too many other things pulling at me.

Soooo... here's what i'm gonna do. @jvashishtha I'm just gonna give you commit access. I'd appreciate it if you do your best to follow the style and philosophy of the project and make sure that stuff that gets merged in doesn't break anything for the thousands of users of this project. I have no doubt you'll be careful.

Have at it, dude :)

**Comment by jogi** [comment]
@HenrikJoreteg Awesome! I will look into it right away. Has been a while ;) Do you want me to rebuild the files with latest mustache (0.7.2) if all tests pass?

**Comment by HenrikJoreteg** [comment]
Sounds good to me. But, it's your call :)   

Also, don't forget to add yourself as a contributor in the readme and docs, if you so wish.  

I've tried to keep a bit of changelog going.

The site (http://icanhazjs.com/) is generated off the gh-pages branch using github's awesome "github pages" stuff.  

However... right now, it's still built off the one on andyet's github (I'll move that over once you tell me it's ready, if you wanna do it, that is).

We originally had all &yetis keep OS projects on our corporate account, but we decided to move to people's personal ones because they're the maintainers anyway. So... anyway, it just hasn't been changed because... well... it's hasn't.  

Once you're happy with it, I'll be happy to switch the CNAME so it the GH pages get generated off this repo.  

Cheers! I'm excited to have some help!
- Henrik

**Comment by jogi** [comment]
Not upgrading to Mustache 0.7.2 for now as it breaks partials support. Will look into it in details this weekend.

**Comment by jogi** [comment]
@HenrikJoreteg gh-pages fixed. Check it out here - http://projects.joreteg.com/ICanHaz.js/. Added changelog for 0.10.1 and 0.10.2 too.

**Comment by HenrikJoreteg** [comment]
Looks like it's all updated: http://icanhazjs.com/

Nice!

**Pull request merged**
