### PR TITLE
add overwriteDuplicates

### PR DESCRIPTION
**Pull request by sylvainpolletvillard**
add overwriteDuplicates parameter
test initial ICanHaz properties for template names

related to issue: https://github.com/HenrikJoreteg/ICanHaz.js/issues/51

### CODE REVIEW

**Comment by sylvainpolletvillard** [comment]
I would appreciate if this could be integrated. It is difficult for me to follow the updates and redo minified builds while keeping these changes

**Comment by HenrikJoreteg** [comment]
How are you using this? seems like maybe "overrideDuplicates" would just be an option to the grabTemplates method.

**Comment by sylvainpolletvillard** [comment]
Indeed, this is a better idea. My first thought was a configuration flag which people could manually set to true.

**Comment by HenrikJoreteg** [comment]
if you update this, PR we can get it merged

**Comment by HenrikJoreteg** [comment]
Sorry this has been sitting too long, I'm not actively using this project and have been having trouble keeping up with maintenance, would be happy to add you if you're interested: https://github.com/HenrikJoreteg/ICanHaz.js/issues/81

Since it's so old, i'm going to close this, feel free to re-open if it's still relevant.

**Pull request closed without merging**
